### ISSUE TITLE
Question about Datacenter metrics aggregation

### ISSUE THREAD

**Issue by allisthere2love** [criteo/cassandra_exporter#20]
Hi, I'm fairly new to the the exporter/prometheus world, looking for an alternative to Opscenter.
In Opscenter we can get metrics per IP, or per datacenter, consolidating all the IPs of that DC.
Is it something possible with this exporter?

**Comment by erebe** [comment]
Hello,
As you need to run one exporter per cassandra node, you will get all the metrics per IP without further efforts. After this, it is easy to create prometheus query in order to aggregate per DC.
You can take a look at the grafana dashboard provided in the repository. All metrics are aggregated by cluster by default, but there is hidden queries in order to drill down by nodes.
If you need to aggregate all clusters per DC, it will be possible, you will just need to tweak the queries.

**Comment by allisthere2love** [comment]
Thank you, I wasn't aware of the 6400 dashboard yet, that's great!
