### ISSUE TITLE
Upgraded to 2.0 and now cassandra 2.1.13 dont distinguish DC

### ISSUE THREAD

**Issue by landepooja** [criteo/cassandra_exporter#22]
Upgraded to 2.0 and now cassandra 2.1.13 dont distinguish DC .
Showing blank datacenter name and cluster name.

**Comment by erebe** [comment]
Hello,
In the 1.x version the information of the datacenter and the cluster name was not retrieved/exported. If you had the information regarding the dc/cluster_name if was due to your prometheus scraping config. So if you want to retrieve them, you need to change your scraping config to either give a different label name to your datacenter/cluster one, or specify that you want to override those labels by yours.

Regarding why the datacenter label is blank, this is due to the fact that this information is not retrievable before cassandra 2.2.
There is no harm at letting this label blank, but if it bother you, you can specify to drop it in your prometheus scrapping config.

P.S: Cassandra 2.1.x will not be supported as it's an end of life version

Let me know if this ok for you

**Comment by landepooja** [comment]
Thank you , you can close this issue.
