### ISSUE TITLE
Is it possible to actually make use of labels?

### ISSUE THREAD

**Issue by wy100101** [criteo/cassandra_exporter#26]
There is a lot of good stuff here, but I hate that it lumps everything under cassandra_stats with the name label looking like a full graphite path that is ':' separated.  This stuff should be broken into multiple metrics with multiple labels to really leverage prometheus.  Does the exporter support the JMX exporters ability to change the exported metric format?

**Comment by erebe** [comment]
> I hate that it lumps everything under cassandra_stats
What issue does it cause you ?

I made this decision in order for the exporter to be compatible with Cassandra 2.2/3.x and to be able to  support future 4.X without efforts/maintenance/migration.
Cassandra export a freaking ton of metrics and except if you want to label everything, still be able to support versions, and having an insane configuration file like JMX exporter, you will end-up anyway dumping a lot of them into a `various` label because you can't tell upfront.

> Does the exporter support the JMX exporters ability to change the exported metric format ?
No, but you can do it in the scrap configuration of prometheus, by using the re-label feature. We do it to aggregate same key metrics by cluster/DC

**Comment by erebe** [comment]
https://github.com/criteo/cassandra_exporter#design-explanation
