### ISSUE TITLE
I Can't build project

### ISSUE THREAD

**Issue by SnailJie** [criteo/cassandra_exporter#27]
Hi:
   I download this project, and build by gradle like 
   " gradle build"

But there have some problems, the error show as :

 > Could not resolve all artifacts for configuration ':classpath'.
   > Could not download shadow.jar (com.github.jengelman.gradle.plugins:shadow:2.0.1)
      > Could not get resource 'https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/2.0.1/shadow-2.0.1.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/2.0.1/shadow-2.0.1.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/52.222.217.47, d29vzk4ow07wi7.cloudfront.net/52.222.217.83, d29vzk4ow07wi7.cloudfront.net/52.222.217.198, d29vzk4ow07wi7.cloudfront.net/52.222.217.210] failed: Read timed out

Seems the shadow-2.0.1.jar needs some dependences.But  I can use URL"https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/2.0.1/shadow-2.0.1.jar"  download this jar.

So I don't know how to fix this.  Can you tell me how to build success?

thanks a lot .

**Comment by erebe** [comment]
Hello,

The build is working fine, a travis build as a proof https://travis-ci.org/criteo/cassandra_exporter/jobs/428962002, also I can build it without hickups on my machine.

Regarding your issue, the only way  I can think of  for this to fail, is that you are in a protected network and that you are using a proxy that do not allow you to download from jcenter.
You can in your gradle config or ~/.m2 config.xml if you are using a proxy when trying to build java apps.
If you are not using a proxy, well that mean your browser is using one, which explains why you can get the jar from it.  In this case, you should look to into gradle config in order to tell it to use your proxy

**Comment by SnailJie** [comment]
> Hello,
> 
> The build is working fine, a travis build as a proof https://travis-ci.org/criteo/cassandra_exporter/jobs/428962002, also I can build it without hickups on my machine.
> 
> Regarding your issue, the only way I can think of for this to fail, is that you are in a protected network and that you are using a proxy that do not allow you to download from jcenter.
> You can in your gradle config or ~/.m2 config.xml if you are using a proxy when trying to build java apps.
> If you are not using a proxy, well that means your browser is using one, which explains why you can get the jar from it. In this case, you should look to into gradle config in order to tell it to use your proxy.

Cool ,I think the problem must be proxy, I need to check it out.
I am so appreciate  your replay, thanks again
