### ISSUE TITLE
Run with Cassandra in Container?

### ISSUE THREAD

**Issue by nearmiss** [criteo/cassandra_exporter#32]
How is this meant to be run if you already have Cassandra in a docker container, if it can't be a javaagent like jmx_exporter?

**Comment by erebe** [comment]
Thanks for the help @allisthere2love :)

@nearmiss you can either change the environnement variable `CASSANDRA_EXPORTER_CONFIG_host` to target a remote cassandra node
or you can start your container within the same network layer than Cassandra in order to be able to contact `localhost`. The easiest way to do that is to start the container with the options `--net=host` https://docs.docker.com/network/network-tutorial-host/

Let's us know if it was not really the question

**Comment by erebe** [comment]
re-open if needed
